name: Check Code Quality

on:
  pull_request:
    branches: [main]
    types:
      - opened
      - synchronize
      - reopened
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repository code
      - name: Checkout Repository
        uses: actions/checkout@v4

      # 2. Set up JDK 26 environment
      - name: Set up JDK 26
        uses: actions/setup-java@v4
        with:
          java-version: "26"
          distribution: "temurin"

      # 3. Check code formatting style (fails instantly if any file mismatches)
      - name: Check Java Code Formatting Style
        run: |
          curl -L -s -o google-java-format.jar https://github.com/google/google-java-format/releases/download/v1.35.0/google-java-format-1.35.0-all-deps.jar

          if ! find src/ -name "*.java" | xargs java -jar google-java-format.jar --set-exit-if-changed --dry-run; then
            echo "==================================================="
            echo " [FAIL] Style guide mismatch detected."
            echo " Please run 'ci.bat' locally to check for more detail."
            echo "==================================================="
            exit 1
          fi

      # 4. Compile the application with Ant
      - name: Build JAR with Ant
        run: ant jar
